### PR TITLE
Docker build without npm repo

### PR DESCRIPTION
**Pull request by oliverdain**
@rprieto as per discussion in #114 you wanted a way to build a Docker container from only those bits that would be available from the npm repo. However, I think you agreed with me that it'd be nice to be able to build the container without first pushing to the npm repo. I think this PR satisfies both goals. Let me know what you think.

### CODE REVIEW

**Comment by rprieto** [comment]
Thanks! After your last comment I was looking into it too 😃 

Your solution seems very clean. I was also thinking about using `npm pack`. One nice thing is being able to cache the install step when working locally:

```bash
# ------------------------------------------------
# Builder image
# ------------------------------------------------

FROM thumbsupgallery/build:alpine as build

# Install thumbsup locally
WORKDIR /thumbsup
COPY package.json package.json
RUN npm install --production      # <---- this is typically cacheable for a long time
COPY . .
RUN npm pack
RUN mkdir package && tar --strip-components=1 -zxf thumbsup-*.tgz -C package

# ------------------------------------------------
# Runtime image
# ------------------------------------------------

FROM thumbsupgallery/runtime:alpine

# Use tini as an init process
# to ensure all child processes (ffmpeg...) are always terminated properly
RUN apk add --update tini
ENTRYPOINT ["tini", "-g", "--"]

# Copy the thumbsup files to the new image
WORKDIR /thumbsup
COPY --from=build /thumbsup/package /thumbsup
COPY --from=build /thumbsup/node_modules /thumbsup/node_modules
RUN ln -s /thumbsup/bin/thumbsup.js /usr/local/bin/thumbsup

# Default command, should be overridden during <docker run>
CMD ["thumbsup"]
```

What do you think?

**Comment by rprieto** [comment]
Sorry just saw your second message now. It looks like the `npm install` step installs thumbsup in `/thumbsup/node_modules/thumbsup`, so everything is shifted. I'll have a think about it too.

**Comment by rprieto** [comment]
After some testing, this is due to the theme-resolving mechanism introduced after 2.4.0. It's great that your Docker build surfaced this error. I'll fix this, but in the meantime your best bet is to build a Docker image from v2.4.0. Your Dockerfile should work well for that.

Also, because your Dockerfile (which simulates an actual `npm install`) surfaced the issue but mine didn't, I'd say let's use your method! 👍

**Comment by rprieto** [comment]
Hi @oliverdain, I'm ready to merge your PR. Could you please amend your PR to remove `--build-args` from `.travis.yml?

**Comment by rprieto** [comment]
Thanks! I think it's just missing the `.` at the end and the `${}` around the tag name, then good to go.

**Comment by oliverdain** [comment]
Sorry - not following what's missing. Can you give me a line number or some other pointer?

**Comment by rprieto** [comment]
They're both at the end of the `docker build` line.

**Comment by oliverdain** [comment]
Think I got 'em

**Comment by rprieto** [comment]
Hi @oliverdain. Unfortunately I'm having issues with the new Docker build. The `npm install git+file:///...` step seems to pull the `master` branch of that repo. This causes issues:

- on Travis, where the code is checked out in detached head (no master)
- when building locally, and you might be on a branch or even have local changes

I will likely revert to either

- the `npm pack` solution, which bundles exactly what's on disk.
- the `npm install@${version}` solution, which is not ideal for your use case, but was working well otherwise. If I choose that I can include another "local" Dockerfile for testing.

**Pull request merged**
