### PR TITLE
Preserve exif information during import

### PR DESCRIPTION
**Pull request by amcolash**
In addition to the numerous other PRs and code changes I have made to support an exif sidebar, I added this option to the base of thumbsup because of #80. It will require a PR and careful thought for thumbsup/downsize#6.

### CODE REVIEW

**Comment by rprieto** [comment]
Thanks, I think the flag is a good idea. I don't understand the PR though, is there missing code to use that flag? Is this a placeholder for later?

**Comment by amcolash** [comment]
I was assuming that the flag is then used in conjunction with the downsize PR mentioned in my first comment

**Comment by amcolash** [comment]
I added in some more to the PR. I think everything should be set to go, I am going to make some slight modifications to my theme PRs as well.

**Comment by rprieto** [comment]
Thanks @amcolash, I think we're very close! The last 2 things I can think about are:

- For performance reasons, do you think we should only write the new `metadata.exif` field if the flag is set? This could help keep the memory consumption low if needed, for example thinking of #74 which was about the RAM usage for a very large gallery.
- Maybe we should reserve the name `--preserve-exif` for later. I really like your idea of an option to preserve EXIF in the target images (for another time), and this flag would be a great fit. For the current feature of having EXIF in the data model, what about `--expose-exif` (in the `Website options:` options group)?

This would give a lot of flexibility to the user, either discarding most of the EXIF data (memory friendly, but no EXIF), or keeping it all in memory (memory-hungry), or preserving it in the output files.

Really looking forward to releasing a new version with the EXIF side panel!

**Comment by amcolash** [comment]
I not sure if memory would actually be an issue here since each file has about 15-60 fields in the exif object. Assuming that one gallery page is fully generated at a time in memory before passing off to handlebars./mustache, that is hardy a memory impact. Assuming worst case where all images are in memory for the duration of a gallery page render = 60 fields * 256 bytes per field (high number) * 1000 images / 1024 bytes / 1024 bytes = roughly 15mb (I think I got that math right,, js might add more overhead here though).

Regardless, I added in the conditional so that a theme does not need to worry about passing the options to the thumbnail partial and follows your idea to clean things up. If that thumbnail partial is used, it will always have the needed information and will embed it - regardless of if the lg-exif plugin is used - making this more useful if someone else wanted to have a theme that shows some of that data on the gallery page.

Additionally, I renamed the option (now `embed-exif`) so that things are more clear that the option embeds metadata into the page (reflected in readme as well).

**Comment by rprieto** [comment]
It looks perfect! Thanks again for all your work on the EXIF viewer, it's tricky to get the feature and semantics right but I think it fit really well with the rest of thumbsup now 👍

**Comment by amcolash** [comment]
Perfect, I'm so happy that this is finally getting in. I love thumbsup so it is great that we can have a bit more info on pictures now!

When you get a chance could you merge the 3 theme prs? They add the actual plugin which is the last step I think.

**Pull request merged**
