### PR TITLE
Blackbox theme

### PR DESCRIPTION
**Pull request by b2954**
change thumbsup to thumbsup-blackbox in two files: bin/thumbsup-blackbox.js and package.json

### CODE REVIEW

**Comment by b2954** [comment]
sorry, false request.. just wanted to commit to my fork

**Comment by rprieto** [comment]
No problem! Let me know if you want to share the theme back upstream when you're finished.

**Comment by b2954** [comment]
yes, the builder is really fun and if i get somewhere with the theme i'd be happy to share it back! i was actually wondering how to best integrate a custom theme, without needing to change the current binary... what do you think of adding an empty "custom" folder to the themes dir and adding it as a choice to thumbsup.js?

**Comment by b2954** [comment]
or just getting rid of the defined choices in thumbsup.js, so one can put any folder and name it in the config.json file? or is there a downside to it?

**Comment by rprieto** [comment]
Hi, sorry for the slow reply. Adding support for external themes sounds like a great idea. I think it will have to come with the caveat that the data model might change when you update versions, and any custom theme might need updating. This is the advantage of submitting a theme to be built-in: they are always kept up to date :)

About the mechanism to load custom themes, I'm not sure about making it load any files inside `templates/themes`. The main reason is that `thumbsup` is mostly meant to be used as a binary, installed with `npm install thumbsup`. In that case you want to avoid any changes to `node_modules/thumbsup/*` since they would be overwritten in any upgrade.

It seems you did `git clone` instead, was that specifically to work on your theme? If that's the case, what about the ability to use a custom theme from any location instead, e.g.

```
thumbsup --theme-path ~/thumbsup-blackbox
```

It would still use the standard layout, but should allow you to create as many partials as you want in this folder - and hopefully even re-use some of the default partials (e.g. to render a photo/video thumbnail).

**Pull request closed without merging**
