### PR TITLE
Skip non-existing files

### PR DESCRIPTION
**Pull request by tribut**
- What's the current behaviour? Invalid filenames lead to **all** files being ignored, see #106.
- What does the PR change? Those files are skipped.
- Does it introduce a breaking change for existing users? No.

### CODE REVIEW

**Comment by rprieto** [comment]
I also just remembered that I might have added the `ENOENT` check to handle non-traversable directories, like your `.git` example from https://github.com/thumbsup/thumbsup/issues/74.

Hidden folders should already be taken care of by `dot: false`, but it's worth testing. What about another unit-test with a folder that contains a sub-folder with no read permissions? Let me know if you're happy to add them otherwise I'll have a look.

**Comment by tribut** [comment]
Sure, I'll look at tests.

**Comment by tribut** [comment]
Please have a look. Not sure, if there is some less complicated way to create invalid filenames.

I will open another PR for the "non-traversable" test, because I'm having some questions there :)

**Comment by tribut** [comment]
Note that I'm using `Buffer.from` which has a version requirement of node v5.10. Did not find a required version anywhere, so I'm unsure if that's ok.

**Comment by rprieto** [comment]
Thanks it looks perfect! Supporting Node 5+ seems reasonable to me.

For the filename, could you use `'file2\xfc.jpg'` (using a hex escape sequence)? I'm also curious why Node thinks it's an invalid filename. At least it's great it we can handle it!

**Comment by tribut** [comment]
I tried `file2\xfc.jpg`, but it ended up creating `file2ü.jpg` (that is, it seems to be using latin-1 encoding which is consistent with the description of `\xNN` and converting that to utf-8 when creating the file).

**Comment by rprieto** [comment]
Ah thanks I didn't realise it wouldn't be the same. Character encodings are fun!

I'll have a quick look at the Travis build (_which is failing on master too for an unknown reason - it's a Docker build and it passes locally_) and merge your PR soon.

**Comment by tribut** [comment]
(Just for the record: The `with a path relative to the current directory` test Travis is complaining about is failing for me locally as well)

**Comment by rprieto** [comment]
Thanks for the heads up, it was indeed a case of "works on my machine" :smile:

**Pull request merged**
