### PR TITLE
Add support for nef (Nikon raw) files.

### PR DESCRIPTION
**Pull request by pozix604**
- What's the current behaviour? Does not support Nikon raw files (NEF).
- What does the PR change? Add support for Nikon raw files.
- Does it introduce a breaking change for existing users? No.

### CODE REVIEW

**Comment by rprieto** [comment]
Hi @pozix604, thanks for the PR! That's great, did everything just work with the new glob?
I'll try to release a new version this week.

**Comment by rprieto** [comment]
Hi again, I just tried a sample NEF file locally and got this error:

```bash
Unexpected error Error: Error: Error: Command failed: sh: dcraw: command not found
gm identify: "dcraw" -c -w "..../nikon.nef" > "/var/folders/xg/y8jyd3j80000gq/T/gmOVwEu0".
gm identify: Delegate failed ("dcraw" -c -w "%i" > "%o").
gm identify: Request did not return an image.
```

Did it work well for you?

**Comment by tribut** [comment]
GraphicsMagic automatically calls `dcraw` to convert raw formats (see http://www.graphicsmagick.org/README.html#add-on-libraries-programs). It needs to be installed for that to work, so it should probably be added as a soft runtime dependency similar to `gifsicle`.

However, I would suggest adding some kind of switch to enable/disable this feature as quite a few people have JPGs and RAWs next to each other which means having both in the gallery is redundant.

Other extensions that  `gm` calls `dcraw` for (according to [upstream source](http://hg.code.sf.net/p/graphicsmagick/code/file/209782a0dad1/coders/dcraw.c#l127)): `3FR, ARW, CR2, CRW, DCR, DNG, ERF, K25, KDC, MEF, MRW, NEF, ORF, PEF, RAF, SR2, SRF, X3F`

**Comment by rprieto** [comment]
That makes sense. Good call about the raw/jpeg use case. What about a flag like `--include-ext “nef,cr2”` or a more generic `--raw-formats true` to include all raw formats when indexing the folder?

**Comment by rprieto** [comment]
Hi @pozix604, thanks for your patience. Based on the conversation above, master now has 3 new flags:
- `--include-photos` (default true)
- `--include-videos` (default true)
- `--include-raw-photos` (default false)

**Pull request closed without merging**
